spring.application.name=househub

# -------------------------------------------------
# Datasource (PostgreSQL) Postgresql 16
# -------------------------------------------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/postgresml}
spring.datasource.username=${DB_USERNAME:postgresml}
spring.datasource.password=${DB_PASSWORD:postgresml}
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------
# HikariCP (Production tuning)
# -------------------------------------------------
spring.datasource.hikari.pool-name=space-hikari
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000

# -------------------------------------------------
# JPA / Hibernate
# -------------------------------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# IMPORTANT: let JPA create tables before data.sql runs
spring.jpa.defer-datasource-initialization=true

# -------------------------------------------------
# SQL Initialization
# -------------------------------------------------
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# -------------------------------------------------
# Logging
# -------------------------------------------------
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

# -------------------------------------------------
# Service Properties
# -------------------------------------------------
service.importer.knowledgeBase.source.directory=${HOUSEHUB_KNOWLEDGENASE_SOURCE_DIRECTORY:C:\\workspace\\knowledge-base\\source}
service.importer.knowledgeBase.target.directory=${HOUSEHUB_KNOWLEDGENASE_TARGET_DIRECTORY:C:\\workspace\\knowledge-base\\target}

# -------------------------------------------------
# RAG Configuration with Anthropic Integration
# -------------------------------------------------
langchain4j.anthropic.chat-model.api-key=${CLAUDE_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-sonnet-4-5

spring.ai.postgresml.embedding.options.transformer=distilbert-base-uncased
spring.ai.postgresml.embedding.options.vectorType=PG_ARRAY
spring.ai.postgresml.embedding.options.metadataMode=EMBED
spring.ai.postgresml.embedding.options.kwargs.device=cpu
#spring.ai.postgresml.embedding.create-extension=true

# -------------------------------------------------
# Embedding Executor
# New threads are created up to the corePoolSize
# If the queue is full, more threads are created up to maxPoolSize
# The queue is used before scaling beyond corePoolSize
#       A large queue reduces thread creation
#       A small queue encourages parallelism
# Example:
# First 5 tasks -> executed immediately (5 threads)
# Next 100 tasks -> placed in the queue
# Next 5 tasks -> cause new threads to be created (up to 10)
# Further tasks -> rejected
# -------------------------------------------------
embedding.executor.corePoolSize=5
embedding.executor.maxPoolSize=10
embedding.executor.queueCapacity=100
embedding.executor.threadNamePrefix="assessmentExecutor-"

